# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import embodied_memory_pb2 as embodied__memory__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in embodied_memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmbodiedMemoryServiceStub(object):
    """============================================================================
    Service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddAtom = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/AddAtom',
                request_serializer=embodied__memory__pb2.AddAtomRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.AddAtomResponse.FromString,
                _registered_method=True)
        self.GetAtom = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/GetAtom',
                request_serializer=embodied__memory__pb2.GetAtomRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.GetAtomResponse.FromString,
                _registered_method=True)
        self.DeleteAtom = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/DeleteAtom',
                request_serializer=embodied__memory__pb2.DeleteAtomRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.DeleteAtomResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/Search',
                request_serializer=embodied__memory__pb2.SearchRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.SearchNear = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/SearchNear',
                request_serializer=embodied__memory__pb2.SearchNearRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.SearchNearResponse.FromString,
                _registered_method=True)
        self.SearchTemporal = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/SearchTemporal',
                request_serializer=embodied__memory__pb2.SearchTemporalRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.SearchTemporalResponse.FromString,
                _registered_method=True)
        self.RecordTrajectory = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/RecordTrajectory',
                request_serializer=embodied__memory__pb2.RecordTrajectoryRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.RecordTrajectoryResponse.FromString,
                _registered_method=True)
        self.SearchSimilarTrajectories = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/SearchSimilarTrajectories',
                request_serializer=embodied__memory__pb2.SearchSimilarTrajectoriesRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.SearchSimilarTrajectoriesResponse.FromString,
                _registered_method=True)
        self.IngestSensorFrame = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/IngestSensorFrame',
                request_serializer=embodied__memory__pb2.IngestSensorFrameRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.IngestSensorFrameResponse.FromString,
                _registered_method=True)
        self.SaveModel = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/SaveModel',
                request_serializer=embodied__memory__pb2.SaveModelRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.SaveModelResponse.FromString,
                _registered_method=True)
        self.CheckSelfCollision = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/CheckSelfCollision',
                request_serializer=embodied__memory__pb2.CheckSelfCollisionRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.CheckSelfCollisionResponse.FromString,
                _registered_method=True)
        self.GetCauses = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/GetCauses',
                request_serializer=embodied__memory__pb2.GetCausesRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.GetCausesResponse.FromString,
                _registered_method=True)
        self.GetEffects = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/GetEffects',
                request_serializer=embodied__memory__pb2.GetEffectsRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.GetEffectsResponse.FromString,
                _registered_method=True)
        self.AddWorldObject = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/AddWorldObject',
                request_serializer=embodied__memory__pb2.AddWorldObjectRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.AddWorldObjectResponse.FromString,
                _registered_method=True)
        self.GetWorldObject = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/GetWorldObject',
                request_serializer=embodied__memory__pb2.GetWorldObjectRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.GetWorldObjectResponse.FromString,
                _registered_method=True)
        self.UpdateWorldObjectPose = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/UpdateWorldObjectPose',
                request_serializer=embodied__memory__pb2.UpdateWorldObjectPoseRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.UpdateWorldObjectPoseResponse.FromString,
                _registered_method=True)
        self.SearchWorldObjects = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/SearchWorldObjects',
                request_serializer=embodied__memory__pb2.SearchWorldObjectsRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.SearchWorldObjectsResponse.FromString,
                _registered_method=True)
        self.GetSceneGraph = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/GetSceneGraph',
                request_serializer=embodied__memory__pb2.GetSceneGraphRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.GetSceneGraphResponse.FromString,
                _registered_method=True)
        self.ComputeRelations = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/ComputeRelations',
                request_serializer=embodied__memory__pb2.ComputeRelationsRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.ComputeRelationsResponse.FromString,
                _registered_method=True)
        self.CognitiveSearch = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/CognitiveSearch',
                request_serializer=embodied__memory__pb2.CognitiveSearchRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.CognitiveSearchResponse.FromString,
                _registered_method=True)
        self.IndexConcept = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/IndexConcept',
                request_serializer=embodied__memory__pb2.IndexConceptRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.IndexConceptResponse.FromString,
                _registered_method=True)
        self.AddExperienceEdge = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/AddExperienceEdge',
                request_serializer=embodied__memory__pb2.AddExperienceEdgeRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.AddExperienceEdgeResponse.FromString,
                _registered_method=True)
        self.RunMeditation = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/RunMeditation',
                request_serializer=embodied__memory__pb2.RunMeditationRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.RunMeditationResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/powermem.embodied.EmbodiedMemoryService/GetStats',
                request_serializer=embodied__memory__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=embodied__memory__pb2.GetStatsResponse.FromString,
                _registered_method=True)


class EmbodiedMemoryServiceServicer(object):
    """============================================================================
    Service
    ============================================================================

    """

    def AddAtom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAtom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAtom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchNear(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchTemporal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordTrajectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchSimilarTrajectories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestSensorFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckSelfCollision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCauses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEffects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddWorldObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorldObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWorldObjectPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchWorldObjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSceneGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeRelations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CognitiveSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndexConcept(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddExperienceEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunMeditation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbodiedMemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddAtom': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAtom,
                    request_deserializer=embodied__memory__pb2.AddAtomRequest.FromString,
                    response_serializer=embodied__memory__pb2.AddAtomResponse.SerializeToString,
            ),
            'GetAtom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAtom,
                    request_deserializer=embodied__memory__pb2.GetAtomRequest.FromString,
                    response_serializer=embodied__memory__pb2.GetAtomResponse.SerializeToString,
            ),
            'DeleteAtom': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAtom,
                    request_deserializer=embodied__memory__pb2.DeleteAtomRequest.FromString,
                    response_serializer=embodied__memory__pb2.DeleteAtomResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=embodied__memory__pb2.SearchRequest.FromString,
                    response_serializer=embodied__memory__pb2.SearchResponse.SerializeToString,
            ),
            'SearchNear': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchNear,
                    request_deserializer=embodied__memory__pb2.SearchNearRequest.FromString,
                    response_serializer=embodied__memory__pb2.SearchNearResponse.SerializeToString,
            ),
            'SearchTemporal': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchTemporal,
                    request_deserializer=embodied__memory__pb2.SearchTemporalRequest.FromString,
                    response_serializer=embodied__memory__pb2.SearchTemporalResponse.SerializeToString,
            ),
            'RecordTrajectory': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordTrajectory,
                    request_deserializer=embodied__memory__pb2.RecordTrajectoryRequest.FromString,
                    response_serializer=embodied__memory__pb2.RecordTrajectoryResponse.SerializeToString,
            ),
            'SearchSimilarTrajectories': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchSimilarTrajectories,
                    request_deserializer=embodied__memory__pb2.SearchSimilarTrajectoriesRequest.FromString,
                    response_serializer=embodied__memory__pb2.SearchSimilarTrajectoriesResponse.SerializeToString,
            ),
            'IngestSensorFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestSensorFrame,
                    request_deserializer=embodied__memory__pb2.IngestSensorFrameRequest.FromString,
                    response_serializer=embodied__memory__pb2.IngestSensorFrameResponse.SerializeToString,
            ),
            'SaveModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveModel,
                    request_deserializer=embodied__memory__pb2.SaveModelRequest.FromString,
                    response_serializer=embodied__memory__pb2.SaveModelResponse.SerializeToString,
            ),
            'CheckSelfCollision': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSelfCollision,
                    request_deserializer=embodied__memory__pb2.CheckSelfCollisionRequest.FromString,
                    response_serializer=embodied__memory__pb2.CheckSelfCollisionResponse.SerializeToString,
            ),
            'GetCauses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCauses,
                    request_deserializer=embodied__memory__pb2.GetCausesRequest.FromString,
                    response_serializer=embodied__memory__pb2.GetCausesResponse.SerializeToString,
            ),
            'GetEffects': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEffects,
                    request_deserializer=embodied__memory__pb2.GetEffectsRequest.FromString,
                    response_serializer=embodied__memory__pb2.GetEffectsResponse.SerializeToString,
            ),
            'AddWorldObject': grpc.unary_unary_rpc_method_handler(
                    servicer.AddWorldObject,
                    request_deserializer=embodied__memory__pb2.AddWorldObjectRequest.FromString,
                    response_serializer=embodied__memory__pb2.AddWorldObjectResponse.SerializeToString,
            ),
            'GetWorldObject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorldObject,
                    request_deserializer=embodied__memory__pb2.GetWorldObjectRequest.FromString,
                    response_serializer=embodied__memory__pb2.GetWorldObjectResponse.SerializeToString,
            ),
            'UpdateWorldObjectPose': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWorldObjectPose,
                    request_deserializer=embodied__memory__pb2.UpdateWorldObjectPoseRequest.FromString,
                    response_serializer=embodied__memory__pb2.UpdateWorldObjectPoseResponse.SerializeToString,
            ),
            'SearchWorldObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchWorldObjects,
                    request_deserializer=embodied__memory__pb2.SearchWorldObjectsRequest.FromString,
                    response_serializer=embodied__memory__pb2.SearchWorldObjectsResponse.SerializeToString,
            ),
            'GetSceneGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSceneGraph,
                    request_deserializer=embodied__memory__pb2.GetSceneGraphRequest.FromString,
                    response_serializer=embodied__memory__pb2.GetSceneGraphResponse.SerializeToString,
            ),
            'ComputeRelations': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeRelations,
                    request_deserializer=embodied__memory__pb2.ComputeRelationsRequest.FromString,
                    response_serializer=embodied__memory__pb2.ComputeRelationsResponse.SerializeToString,
            ),
            'CognitiveSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.CognitiveSearch,
                    request_deserializer=embodied__memory__pb2.CognitiveSearchRequest.FromString,
                    response_serializer=embodied__memory__pb2.CognitiveSearchResponse.SerializeToString,
            ),
            'IndexConcept': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexConcept,
                    request_deserializer=embodied__memory__pb2.IndexConceptRequest.FromString,
                    response_serializer=embodied__memory__pb2.IndexConceptResponse.SerializeToString,
            ),
            'AddExperienceEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.AddExperienceEdge,
                    request_deserializer=embodied__memory__pb2.AddExperienceEdgeRequest.FromString,
                    response_serializer=embodied__memory__pb2.AddExperienceEdgeResponse.SerializeToString,
            ),
            'RunMeditation': grpc.unary_unary_rpc_method_handler(
                    servicer.RunMeditation,
                    request_deserializer=embodied__memory__pb2.RunMeditationRequest.FromString,
                    response_serializer=embodied__memory__pb2.RunMeditationResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=embodied__memory__pb2.GetStatsRequest.FromString,
                    response_serializer=embodied__memory__pb2.GetStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'powermem.embodied.EmbodiedMemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('powermem.embodied.EmbodiedMemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbodiedMemoryService(object):
    """============================================================================
    Service
    ============================================================================

    """

    @staticmethod
    def AddAtom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/AddAtom',
            embodied__memory__pb2.AddAtomRequest.SerializeToString,
            embodied__memory__pb2.AddAtomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAtom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/GetAtom',
            embodied__memory__pb2.GetAtomRequest.SerializeToString,
            embodied__memory__pb2.GetAtomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAtom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/DeleteAtom',
            embodied__memory__pb2.DeleteAtomRequest.SerializeToString,
            embodied__memory__pb2.DeleteAtomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/Search',
            embodied__memory__pb2.SearchRequest.SerializeToString,
            embodied__memory__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchNear(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/SearchNear',
            embodied__memory__pb2.SearchNearRequest.SerializeToString,
            embodied__memory__pb2.SearchNearResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchTemporal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/SearchTemporal',
            embodied__memory__pb2.SearchTemporalRequest.SerializeToString,
            embodied__memory__pb2.SearchTemporalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordTrajectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/RecordTrajectory',
            embodied__memory__pb2.RecordTrajectoryRequest.SerializeToString,
            embodied__memory__pb2.RecordTrajectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchSimilarTrajectories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/SearchSimilarTrajectories',
            embodied__memory__pb2.SearchSimilarTrajectoriesRequest.SerializeToString,
            embodied__memory__pb2.SearchSimilarTrajectoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestSensorFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/IngestSensorFrame',
            embodied__memory__pb2.IngestSensorFrameRequest.SerializeToString,
            embodied__memory__pb2.IngestSensorFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/SaveModel',
            embodied__memory__pb2.SaveModelRequest.SerializeToString,
            embodied__memory__pb2.SaveModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckSelfCollision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/CheckSelfCollision',
            embodied__memory__pb2.CheckSelfCollisionRequest.SerializeToString,
            embodied__memory__pb2.CheckSelfCollisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCauses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/GetCauses',
            embodied__memory__pb2.GetCausesRequest.SerializeToString,
            embodied__memory__pb2.GetCausesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEffects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/GetEffects',
            embodied__memory__pb2.GetEffectsRequest.SerializeToString,
            embodied__memory__pb2.GetEffectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddWorldObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/AddWorldObject',
            embodied__memory__pb2.AddWorldObjectRequest.SerializeToString,
            embodied__memory__pb2.AddWorldObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorldObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/GetWorldObject',
            embodied__memory__pb2.GetWorldObjectRequest.SerializeToString,
            embodied__memory__pb2.GetWorldObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateWorldObjectPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/UpdateWorldObjectPose',
            embodied__memory__pb2.UpdateWorldObjectPoseRequest.SerializeToString,
            embodied__memory__pb2.UpdateWorldObjectPoseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchWorldObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/SearchWorldObjects',
            embodied__memory__pb2.SearchWorldObjectsRequest.SerializeToString,
            embodied__memory__pb2.SearchWorldObjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSceneGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/GetSceneGraph',
            embodied__memory__pb2.GetSceneGraphRequest.SerializeToString,
            embodied__memory__pb2.GetSceneGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeRelations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/ComputeRelations',
            embodied__memory__pb2.ComputeRelationsRequest.SerializeToString,
            embodied__memory__pb2.ComputeRelationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CognitiveSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/CognitiveSearch',
            embodied__memory__pb2.CognitiveSearchRequest.SerializeToString,
            embodied__memory__pb2.CognitiveSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IndexConcept(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/IndexConcept',
            embodied__memory__pb2.IndexConceptRequest.SerializeToString,
            embodied__memory__pb2.IndexConceptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddExperienceEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/AddExperienceEdge',
            embodied__memory__pb2.AddExperienceEdgeRequest.SerializeToString,
            embodied__memory__pb2.AddExperienceEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunMeditation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/RunMeditation',
            embodied__memory__pb2.RunMeditationRequest.SerializeToString,
            embodied__memory__pb2.RunMeditationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/powermem.embodied.EmbodiedMemoryService/GetStats',
            embodied__memory__pb2.GetStatsRequest.SerializeToString,
            embodied__memory__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
